version: "3"
name: orchestrator
services:
  maas:
    image: ${DOCKER_REGISTRY}/maas:${MAAS_TAG}
    build:
      context: .
      tags:
        - ${DOCKER_REGISTRY}/maas:${MAAS_TAG}
        - ${DOCKER_REGISTRY}/maas:latest
    hostname: ${MAAS_HOSTNAME}
    container_name: ${MAAS_HOSTNAME}
    environment:
      TZ: Europe/Madrid
      DEBUG: ${DEBUG}
      MEDIA_ROOT: ${MAAS_MEDIA_ROOT:-/usr/application/storage/files}
      MEDIA_URL: ${MAAS_MEDIA_URL:-/usr/application/storage/files}
      ALLOWED_HOSTS: ${MAAS_ALLOWED_HOSTS}
      VALID_DATA_PARTNERS: ${VALID_DATA_PARTNERS}
      #VALID_AI_ENGINE_FUNCTIONALITIES: ${VALID_AI_ENGINE_FUNCTIONALITIES}
      VALID_AI_ENGINE_DATA_TYPES: ${VALID_AI_ENGINE_DATA_TYPES}
      VALID_AI_ENGINE_ROLE_TYPES: ${VALID_AI_ENGINE_ROLE_TYPES}
      # New: define the gunicorn arguments as an environment variable
      GUNICORN_CMD_ARGS: ${MAAS_GUNICORN_CMD_ARGS}
    # Mount paths for sqlite db and orchestration init script
    volumes:
      - ${MAAS_STORAGE_LOCAL_PATH}:/usr/application/storage
    networks:
      incisive:
  
  # alpine for debugging purposes
  alpine:
    image: alpine/curl:latest
    hostname: alpine
    container_name: alpine
    environment:
      TZ: Europe/Madrid
    command:
      - sleep
      - infinity
    volumes:
      - '${MAAS_SCRIPTS}:/maas_scripts'
      - '${MAAS_SCRIPTS_POPULATED}:/maas_scripts_populated'
    networks:
      incisive:

networks:
  incisive:
    name: incisive
    driver: bridge
