# Generated by Django 3.2.9 on 2022-03-28 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIEngine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('container_name', models.CharField(max_length=200)),
                ('container_version', models.CharField(max_length=50)),
                ('owner', models.CharField(max_length=200)),
                ('job_use_cases', models.CharField(max_length=200)),
                ('data_query', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('default_job_config_training_from_scratch', models.FileField(blank=True, null=True, upload_to='ai_engines/training_from_scratch_configs')),
                ('default_job_config_training_from_pretrained_model', models.FileField(blank=True, null=True, upload_to='ai_engines/training_from_pretrained_model_configs')),
                ('default_job_config_evaluating_from_pretrained_model', models.FileField(null=True, upload_to='ai_engines/evaluating_from_pretrained_model_configs')),
                ('default_job_config_merging_models', models.FileField(blank=True, null=True, upload_to='ai_engines/merging_models_configs')),
                ('default_job_config_inferencing_from_pretrained_model', models.FileField(blank=True, null=True, upload_to='ai_engines/inferencing_from_pretrained_model_configs')),
            ],
            options={
                'unique_together': {('container_name', 'container_version')},
            },
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=50)),
                ('data_hash', models.CharField(max_length=256)),
                ('data_partners_patients', models.TextField(null=True)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model_files', models.FileField(upload_to='models')),
                ('ai_engine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.aiengine')),
                ('parent_model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.model')),
            ],
            options={
                'unique_together': {('name', 'ai_engine', 'data_hash')},
            },
        ),
        migrations.CreateModel(
            name='InferenceResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execution_id', models.IntegerField()),
                ('result_files', models.FileField(upload_to='inference_results')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('execution_id',)},
            },
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('data_hash', models.CharField(max_length=256)),
                ('data_partner', models.CharField(max_length=256)),
                ('data_partner_patients', models.TextField()),
                ('value', models.FloatField()),
                ('description', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.model')),
            ],
            options={
                'unique_together': {('name', 'model', 'data_hash')},
            },
        ),
    ]
