# Generated by Django 4.1.7 on 2023-02-27 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIEngine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('container_name', models.CharField(max_length=200)),
                ('owner', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('data_type', models.TextField()),
                ('role_type', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_considerations', models.TextField(null=True)),
                ('trl', models.CharField(max_length=200, null=True)),
                ('ethics', models.TextField(null=True)),
                ('caveats', models.TextField(null=True)),
                ('metrics', models.TextField(null=True)),
                ('license', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AIEngineVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_version', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('functionalities', models.TextField()),
                ('explains', models.BooleanField()),
                ('default_user_vars_training_from_scratch', models.FileField(null=True, upload_to='ai_engines/training_from_scratch_user_vars')),
                ('default_user_vars_training_from_pretrained_model', models.FileField(null=True, upload_to='ai_engines/training_from_pretrained_model_user_vars')),
                ('default_user_vars_evaluating_from_pretrained_model', models.FileField(null=True, upload_to='ai_engines/evaluating_from_pretrained_model_user_vars')),
                ('default_user_vars_merging_models', models.FileField(null=True, upload_to='ai_engines/merging_models_user_vars')),
                ('default_user_vars_inferencing_from_pretrained_model', models.FileField(null=True, upload_to='ai_engines/inferencing_from_pretrained_model_user_vars')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ai_engine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='main.aiengine')),
            ],
            options={
                'unique_together': {('ai_engine', 'container_version')},
            },
        ),
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_engine_version_user_vars', models.FileField(upload_to='ai_models/user_vars')),
                ('name', models.CharField(max_length=200)),
                ('data_hash', models.CharField(max_length=256, null=True)),
                ('data_partners_patients', models.TextField(null=True)),
                ('merge_type', models.CharField(max_length=50, null=True)),
                ('description', models.TextField()),
                ('contents', models.FileField(upload_to='ai_models/contents')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ai_engine_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.aiengineversion')),
                ('parent_ai_model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.aimodel')),
            ],
            options={
                'unique_together': {('name', 'ai_engine_version', 'data_hash')},
            },
        ),
        migrations.CreateModel(
            name='GenericFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contents', models.FileField(upload_to='generic_files')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('data_hash', models.CharField(max_length=256)),
                ('data_partners_patients', models.TextField()),
                ('value', models.FloatField()),
                ('description', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ai_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.aimodel')),
            ],
            options={
                'unique_together': {('name', 'ai_model', 'data_hash')},
            },
        ),
    ]
